import type { Route } from "@lifi/sdk";
import type { RangoPayload } from "../aggregators/rango/types";
export type ProviderName = "lifi" | "socket" | "rango";
export type ProviderSelection = Record<ProviderName, boolean>;
type RouteBase = {
  id: string;
  fromChainId: number;
  toChainId: number;
  fromTokenAddress: string;
  toTokenAddress: string;
  fromAddress: string;
  fromAmount: string;
  toAmount: string;
  toAmountMin: string;
  gasCostUSD: string | null;
  toolLabel: string;
  durationSeconds: number;
  expiresAt: number;
};
export type LifiNormalizedRoute = RouteBase & { provider: "lifi"; raw: Route };
export type RangoNormalizedRoute = RouteBase & { provider: "rango"; raw: RangoPayload };
export type NormalizedRoute = LifiNormalizedRoute | RangoNormalizedRoute;
